export const resentSales = {
  heading: 'Recent Sales',
  filter: 'Today',
  filterNav: [
    { id: '1', text: 'Today' },
    { id: '2', text: 'This Month' },
    { id: '3', text: 'This Year' },
  ],
  data: [
    [2644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [2147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [2457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [2049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [2644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [3644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [3147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [3457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [3049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [3644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [4644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [4147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [4457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [4049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [4644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [5644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [5147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [5457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [5049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [5644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [6644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [6147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [6457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [6049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [6644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [7644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [7147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [7457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [7049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [7644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [8644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [8147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [8457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [8049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [8644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [9644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [9147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [9457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [9049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [9644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [10644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [10147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [10457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [10049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [10644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [11644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [11147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [11457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [11049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [11644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [12644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [12147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [12457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [12049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [12644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
    [13644, 'Raheem Lehner', 'Sunt similique distinctio', '$165', 'approved'],
    [13147, 'Bridie Kessler', 'Blanditiis dolor omnis similique', '$47', 'pending'],
    [13457, 'Brandon Jacob', 'At praesentium minu', '$64', 'approved'],
    [13049, 'Ashleigh Langosh', 'At recusandae consectetur', '	$147', 'approved'],
    [13644, 'Angus Grady', 'Ut voluptatem id earum et', '$67', 'rejected'],
  ],
}
