export const withSeparatorAlerts = {
  heading: 'With Heading & Separator',
  alerts: [
    {
      id: '1',
      heading: 'Primary Heading',
      text: 'Et suscipit deserunt earum itaque dignissimos recusandae dolorem qui. Molestiae rerum perferendis laborum. Occaecati illo at laboriosam rem molestiae sint.',
      subtext: 'Temporibus quis et qui aspernatur laboriosam sit eveniet qui sunt.',
      type: 'primary',
    },
    {
      id: '2',
      heading: 'Secondary Heading',
      text: 'Et suscipit deserunt earum itaque dignissimos recusandae dolorem qui. Molestiae rerum perferendis laborum. Occaecati illo at laboriosam rem molestiae sint.',
      subtext: 'Temporibus quis et qui aspernatur laboriosam sit eveniet qui sunt.',
      type: 'secondary',
    },
    {
      id: '3',
      heading: 'Success Heading',
      text: 'Et suscipit deserunt earum itaque dignissimos recusandae dolorem qui. Molestiae rerum perferendis laborum. Occaecati illo at laboriosam rem molestiae sint.',
      subtext: 'Temporibus quis et qui aspernatur laboriosam sit eveniet qui sunt.',
      type: 'success',
    },
    {
      id: '4',
      heading: 'Danger Heading',
      text: 'Et suscipit deserunt earum itaque dignissimos recusandae dolorem qui. Molestiae rerum perferendis laborum. Occaecati illo at laboriosam rem molestiae sint.',
      subtext: 'Temporibus quis et qui aspernatur laboriosam sit eveniet qui sunt.',
      type: 'danger',
    },
    {
      id: '5',
      heading: 'Warning Heading',
      text: 'Et suscipit deserunt earum itaque dignissimos recusandae dolorem qui. Molestiae rerum perferendis laborum. Occaecati illo at laboriosam rem molestiae sint.',
      subtext: 'Temporibus quis et qui aspernatur laboriosam sit eveniet qui sunt.',
      type: 'warning',
    },
    {
      id: '6',
      heading: 'Info Heading',
      text: 'Et suscipit deserunt earum itaque dignissimos recusandae dolorem qui. Molestiae rerum perferendis laborum. Occaecati illo at laboriosam rem molestiae sint.',
      subtext: 'Temporibus quis et qui aspernatur laboriosam sit eveniet qui sunt.',
      type: 'info',
    },
    {
      id: '7',
      heading: 'Light Heading',
      text: 'Et suscipit deserunt earum itaque dignissimos recusandae dolorem qui. Molestiae rerum perferendis laborum. Occaecati illo at laboriosam rem molestiae sint.',
      subtext: 'Temporibus quis et qui aspernatur laboriosam sit eveniet qui sunt.',
      type: 'light',
    },
    {
      id: '8',
      heading: 'Dark Heading',
      text: 'Et suscipit deserunt earum itaque dignissimos recusandae dolorem qui. Molestiae rerum perferendis laborum. Occaecati illo at laboriosam rem molestiae sint.',
      subtext: 'Temporibus quis et qui aspernatur laboriosam sit eveniet qui sunt.',
      type: 'dark',
    },
  ],
}
